#!/bin/sh
BASEDIR=`dirname $0`
#FIRM=$BASEDIR/firm
#INSTALLJAR=$BASEDIR/install.jar
#printf "当前路径 $BASEDIR\n"
#printf "install路径 $INSTALLJAR\n"
#if [ ! -d $FIRM ]; then  
#	printf "firm目录不存在\n"
#	cd $BASEDIR
#	printf "开始解压\n"
#	exec java -jar $INSTALLJAR
#else
#	printf "firm目录存在"
#	cd $BASEDIR/firm
#	exec java -jar -XstartOnFirstThread main.jar
#fi

	cd $BASEDIR
	exec java/bin/java -jar jiagu.jar